---
title: "Tax Morale in Africa"
author: "Wiebke Weiger & Jasmin Cantzler"
date: "11. Oktober 2015"
output: html_document
bibliography: References.bib
---
[@Cummings2009]

#### 1. Overview: Introduction & Policy Relevance, Research Question, Data Sources & Preliminary Structure of Collaborative Research Project

**Introduction & Policy Relevance**: tax evasion is considered a social malady across countries and is often thought to be one of the bigger obstacles to inclusive economic growth. High levels of evasion lead to a misallocation of resources and hinder the ability of the government to invest in the provision of public goods. Therefore, understanding the rationale behind tax evaders, or compliers, becomes essential to national development and state-building. Identifying and conceptualizing trends will open the possibility for governments to effectively and efficiently tackle tax evasion. The current tax compliance literature lacks research on the degree of tax morale in developing countries. This paper aims to tap into this gap, focusing on African countries, analysing tax morale as a dependent variable to investigate the determinants that systemically affect tax morale.

**Research Question**: We want to investigate the determinants of tax morale in Africa. 

**Data Sources**: We want to use data gathered by the Afrobarometer [http://www.afrobarometer.org/ "Afrobarometer"] 

**Preliminary Structure of Collaborative Research Project**:
(die Aufzählung ist alles in einer Linie :( weißt du wie man das so bekommt wie es hier aussieht?))
1. Introduction
2. Literature Review
3. Method
4. Results and Discussion
5. Conclusion

#### 2. Literature Review and Research Gap Identification
In 1972, Allingham and Sandmo presented a formal model explaining tax evasion as a negative correlation with the probability of detection and the degree of punishment. According to their model, rational individuals should report virtually no income. In later years, their model turned out to have little explanatory power and failed to explain the high degree of tax compliance in some countries despite their low level of deterrence. This puzzle of tax compliance and the limitations of deterrence models led to an increasing literature acknowledging the need to consider other non-economic factors, such as psychological, moral and social factors. One widely used concept to be included in the economics of crime model is that of tax morale. Tax morale is often defined as “the existence of an intrinsic motivation to pay taxes” (Torgler, 2005; Torgler & Schneider, 2009; Cummings, Martinez-Vazquez, McKee, & Torgler, 2009). While there are many other definitions out there, this is the one most commonly used. Despite the absence of a common definition of tax morale, there seems to be an agreement on certain drivers, in particular social norms, values and trust and/or approval of the government seem to have an effect on tax morale. There is strong evidence that tax morale influences tax compliance of individual taxpayers (Maciejovsky, Schwarzenberger, & Kirchler, 2011; Molero & Pujol, 2012; Alm & Torgler, 2006; Duellek et al., 2012).One of the major shortcomings of the current literature debate is that little research has been conducted in developing countries. This research paper thus aims to (at least partially) close this gap by investigating the determinants of tax morale in African countries. 

#### 3. Research Design & Methods
African countries, while different on its own, share certain characteristics, such as colonial past, that render them comparable (work on that argumentation) For the purpose of this project – to analyse a region-, specific institutional and contextual characteristics of the countries will not play a prominent role. On the other hand, emphasis will be made on their shared socio-economic characteristic of being developing nations. The direct consequence of this is that they present low tax-effort indices – revenue collections to estimated revenue potentials – and, therefore, the importance to tackle tax evasion (and avoidance) becomes more urgent. **add tax effort graph Africa**

Moreover, identifying the determinants of tax morale could have interesting implications for policy interventions in compliance matters. For example, studies have shown that (pre-existing) deterrence mechanisms work better when there is a ‘social cost’ attached to them (OECD, 2010). With a thorough literature review, we will argue that this ‘social cost’ can be explained by tax morale. Subsequently, policy strategies aiming at increasing compliance should look at ways of increasing tax morale, appealing to the cooperative (complier) side of the sector, as opposed to increasing deterrence mechanisms which may have counter-intuitive effects – such as more evasion, even when the cost of defecting increases.

In order to carry out the analysis, we will use data from the Afrobarometer, an "African-led, non-partisan survey research project that measures citizen attitudes on democracy and governance, the economy, civil society, and other topics" (insert quote) The Afrobarometer's main donors for the survey rounds 5 and 6 included the Mo Ibrahim Foundation, the Swedish International Development Cooperation Agency, the Department for International Development, the United States Agency for International Development, as well as the World Bank. All interviews are conducted face-to-face and samples usually include either 1200 or 2400 cases per country).


**include information about the survey, the question we will use to measure tax morale as well as some basic information about the number of observations, countries etc.; find out how to include a picture in Markdown (make map of countries included)**

We will then perfom a regression analysis to investigate the determinants of tax morale in Africa.

# References
