---
title: "Opening the Black Box - Determinants of Tax Morale in Africa"
author: "Wiebke Weiger & Jasmin Cantzler"
date: "13 November 2015"
output:
  html_document:
    fig_caption: yes
    number_sections: yes
    toc: yes
  pdf_document:
    fig_caption: yes
    number_sections: yes
    toc: yes
bibliography: References.bib
---
\pagebreak

#Introduction
A country’s ability to efficiently mobilize its national resources is a topic that has recently been gaining traction in the discussion surrounding development; it provides governments with the funds needed to “invest in development, relieve poverty and deliver public services directed toward the physical and social infrastructure required to enhance long term growth” [@OECD2013]

Ever since the Monterrey Consensus was adopted in 2002, in which countries recognized the importance of raising domestic revenues, development aid has been increasingly shifting from direct financial assistance to improving tax systems and national resource management. Unfortunately, up to this date, tax systems still attract relatively little international assistance and “estimates based on OECD data suggests that currently around 0.1% of Official Development Assistance (excluding IMF) goes to support the development of tax systems in developing countries [@OECD2015].

One malady plaguing developing countries is tax evasion and tax avoidance; whereby tax evasion “in general refers to illegal practices to escape from taxation”, whereas tax avoidance “in contrast, takes place within the legal context of the tax systems, that is individuals or firms take advantage of the tax code and exploit “loopholes”, i.e. engage in activities that are legal but run counter to the purpose of the tax law [@GTZ].

High levels of tax evasion lead to a misallocation of resources and hinder the ability of the government to invest in the provision of public goods. Therefore, understanding the rationale behind tax evaders becomes essential to national development and state building. Traditionally, the standard way to explain tax compliance has been the economics-of-crime approach, which assumes a rational taxpayer maximizing his or her utility by balancing the risk of detection and punishment with the benefit of tax evasion. Today, this approach is increasingly regarded as too narrow to fully explain tax compliance, and many argue for the need to include social factors, which are said to explain why people conform to paying taxes even in the absence of strong deterrence mechanisms. These social factors constitute and influence the individual’s “intrinsic motivation to pay taxes,” hereafter referred to as tax morale, by increasing moral costs of tax evasion and thus increasing tax compliance. This link has been increasingly studied and strong evidence has been established that tax morale influences individual tax compliance. **The majority of the studies focus on developed countries and only few studies investigate the determinants of tax morale in developing countries.**  Since tax systems are embedded in national historical events and the cultural particularities, “the existence or creation of a universal and ‘objectively’ good system of taxation becomes implicitly impossible” [@Nerre] and highlights that tax culture is specific to regions and countries and influenced by the interaction of actors and cultural values. On the other hand, there might be universal values, such as condemning corruption and feelings of trust that have a direct influence on tax morale across cultural boundaries. 

The purpose of this paper is to fill the existing gap in research by contributing a study of tax morale in African countries and investigates whether the commonly identified determinants of tax morale also satisfactorily explain this sentiment in African countries, thereby contributing to expanding the limited existing research in the field of tax morale by investigating a geographical area that has been largely neglected. The African Development Bank itself recognizes that tax morale and trust in public institutions are "issues impinging the continent's development" [@ADB]; this paper therefore aims to provide specific findings to African policymakers, which could be used to derive customized policy recommendations. 

Our data comes from the Afrobarometer Survey, and our conceptural framework is based on the commonly identified determinants of tax morale. The paper is organized as follows: Chapter 2 provides a review of the literature, illustrating the conceptual evolution of tax morale and the commonly associated determinants of tax morale; chapter 3 describes the data and methodology, chapter 4 presents the results, its interpretation and discussion; and chapter 5 concludes the study. 

#Literature Review

This chapter reviews the most influential literature about tax morale. We briefly review Allingham and Sandmo’s model of income tax evasion [-@Allingham1972] before discussing how the narrative of tax morale developed over time, how tax morale is defined, what factors are said to determine tax morale and why we make the case that these determinants need to be tested in the context of African countries.

## The Conceptual Evolution of Tax Morale
In 1972, Allingham and Sandmo presented a formal model explaining tax evasion as negatively correlated with the probability of detection and the degree of punishment. According to their model, rational individuals should report virtually no income. Their model turned out to have little explanatory power and failed to account for the high degree of tax compliance in some countries, despite their low level of deterrence. This puzzle of tax compliance is only solvable using alternative theories, empirical findings, and calls for the need to consider other non-economic factors, including psychological, moral and social. Shortly after Allingham and Sandmo published their model, which was influenced by the economics-of-crime approach, Spicer and Lundstedt [-@Spicer] acknowledged that the decision of tax compliance is not solely based on sanctions but also on attitudes and norms. Tax compliance is thus “not only a function of opportunity, tax rates, probability of detection and so on, but of each individual’s willingness to comply, shaped by tax morale” [@Torgler2007, 77]. Tax morale is often defined as “the existence of an intrinsic motivation to pay taxes” [@Cummings2009; @Torgler2005; @Torgler2009]. Over the years several studies shed light on tax morale and find strong evidence that tax morale indeed influences tax compliance [@AlmTorgler; @Dulleck2012; @Maciejovsky2012; @Molero2012]. Tax compliance therefore seems to be not explainable solely by the level of enforcement, but partially by tax morale. What factors then determine tax morale?

## Determinants of Tax Morale
Currently, tax morale remains the underdog in explaining tax compliance and “most studies treat ‘tax morale’ as a black box without discussing or even considering how it might arise or how it might be maintained” [@FeldFrey]. Not surprisingly then, the analysis of tax morale as a dependent variable remains a rather novel topic in tax compliance literature. The relatively few studies aiming to determine what influences tax morale find that factors such as trust in government, the level of corruption, interactions with other taxpayers and tax administrators, tax burden, perception about benefits of public spending, social norms, detection, and punishment all determine tax morale and hence influence tax compliance. 
Trust in government and/or government officials is one of the classic factors said to influence the tax compliance behavior of individuals [@Torgler2001; @Torgler2003; @Torgler2009]. If people have no faith that their taxes are being fairly collected and spent, their desire to comply with applicable taxes is lowered. Similarly, corruption undermines tax morale by promoting a feeling of tax injustice; leading individuals to feel entitled to evade the taxes of an unfair system.  Related to this feeling of injustice are interactions between taxpayers, which subsequently further influence and potentially erode or increase tax morale. Individuals who know of someone avoiding their taxes are found to have lower tax morale than others [@Torgler2005], whereas the knowledge that others are paying their taxes correspondingly can increase tax morale. This suggests that there might be a “positive snowball effect” [@FreyTorgler; @Lewis], whereby taxpayers’ tax morale increases if they perceive others to be more compliant. Tax administrators also form an important figure in determining tax morale; when tax officials treat individuals with respect, their tax morale is enhanced [@BohnetFrey; @FeldFrey2003]. In addition, the perception of the tax burden seems to have an impact on tax morale: according to a study concerning Latin America [@Torgler2005], over 46 percent of respondents stated a high tax burden to be a reason for tax evasion. Based on the author’s findings, self-employed individuals are especially prone to developing anti-tax feelings, as taxes are typically more visible to them and affect them more directly, which results in lower tax morale. At the same time, individuals’ tax morale might also be influenced by their perception of received benefits, in the form of public goods and services. Torgler suggests that there is a direct input-output relation, where individuals compare money paid with benefits received. An additional relevant factor can be fiscal knowledge, which increases tax morale by influencing the perception of received benefits. Better-educated taxpayers are more knowledgeable about tax law and fiscal connections, and ultimately may be better equipped to see the connection between paying taxes and receiving benefits [@Lewis]. 
Furthermore, strongly established social norms [@Ajzen; @Lewis] play a big role in determining the change of tax morale over time. Social dynamics- such as taxpayer interaction- become customary in the long-term, resulting in attitudes that become social norms. Consequently, what becomes central to complying with official laws is not the regulation in itself, but the justification for doing so. When a social norm dictates that allocating tax money into personal projects is morally acceptable, as opposed to giving it to the tax administration, the aforementioned ‘positive snowball effect’ might not be so easy to attain. Traxler [-@Traxler] finds that conditional cooperation is a characteristic inherent in taxpayers, in the sense that they condition their compliance to the behavior of the larger group. Traxler and Winter [-@TraxlerWinter] provide evidence of the existence of social sanctions, for example for an individual who cheats on their taxes when complying is the norm. If this is the case, the logical implication is that there is a need to realign social norms with tax regulations. 

## Tax Morale in Africa
Measuring tax evasion is a complex endeavor and while there are several methods available for attempting to measure tax evasion, using audited returns, traces of true income, and measures of traces of compliance, all of them face the same problem: tax evasion is an informal economic activity and “unlike invisible phenomena in the natural sciences, these invisible social science phenomena are hard to measure because of choices made by individuals” [@Slemrod, 25]. All of these methods face measurement problems, “that arise not by chance, but because of the nature of the subject matter” (p. 50). That said, to give a point of reference to illustrate the widespread dimension of tax evasion, estimates for South Africa state that households fail to declare up to 30% of the income [@ADCORP].In recent years, especially in the aftermath of the global financial crisis the focus has been on tax evasion of cooperations and estimates about private tax evasion is almost non existent. By shifting the focus on to individuals, this paper by no means wants to shift the blame away from multinationals; it rather complements the current debate about taxes, obligation, values and sentiments by including the everyday citizen into this dialogue and quest for morale behavior. **write a few more lines about relevance**

#Method

This study uses a regression analysis to assess the determinants of tax morale in Afria. The following chapter provides a comprehensive explanation about the methods used. We first substantiate our research design by indicating which method was chosen and why before providing information about the participants. In the operationalization section we show how we instrumented our variables, before discussing the analysis procedures we used to process, describe and test our data. This chapter ends with a section discussing the limitations and delimitations of the methods used.

##Design
A regression analysis is used to investigate the determinants of tax morale in Africa, utilizing cross-sectional survey data from the Afrobarometer Survey [@Afro].We reside with Torgler and believe that it "is important to analyse the determinants that influence tax morale in developing countries as the environment is different from developed countries", while on the other hand acknowledging that "some effects might be independent of cultural environments" [@Torgler2005, p.2]. Our conceptual framework is therefore based on the determinants of tax morale in developed countries, whereby:

\begin{equation}
\begin{aligned}
Tax Morale_i = & \alpha_i + \beta_1 Trust in Government/Public Officials_i + \beta_2 Level of Corruption_i \\
& + \beta_3 interactions with other taxpayers_i + \beta_4 tax burden_i \\
& + \beta_5 detection and punishment_i + \beta_5 Social Norms_i + \epsilon_i
\end{aligned}
\end{equation}

$Tax Morale_i$ is a measure of the degree to which the respondent *i* believes the tax department always has the right to make people pay taxes. $Trust in Government/Public Officials_i$ is a measure **...** 
$Level of Corruption_i$ is **...** $Interactions with other taxpayers_i$ is **...** $tax burden_i$ **..** $Social Norms_i$ **..**  $Detection and punishment_i$ *...** $epsilon_i$ denotes a vector of control variables that include the gender, religion, age and **...** of the respondent. Based on the assumptions of our framework we formulate the following hypothesis:

$$H_1: The same determinants have a positive effect on tax compliance in Africa$$
$$H_0: The determinants have no impact on tax morale in Africa$$

##Data Selection
In order to test our hypothesis, we make use of data from the Afrobarometer, an "African-led, non-partisan survey research project that measures citizen attitudes on democracy and governance, the economy, civil society, and other topics" [@Afro]. The Afrobarometer's main donors for the survey rounds 5 and 6 (data on round 6 are not available yet) included the Mo Ibrahim Foundation, the Swedish International Development Cooperation Agency, the Department for International Development, the United States Agency for International Development, as well as the World Bank. All survey interviews are conducted face-to-face by interviewers who usually have a first class degree in social science and who receive training by national partners during a five-day traning workshop which includes the familiarisation of the survey in national and local languages, sampling protocol and field practice. The interviews usualy are conducted within 48 hours after the training [@Afro]. Afrobarometer uses national pribability samples that are designed to generate a represetative cross-sections of the country by using random selection methods and my sampling at all stages with probability proportinate to population size [see @Afro]. In Figure **?** one can see the distribution per country.

```{r, include=FALSE}
##include figure showing respondents per country or another summary statistic
```

##Operationalization
In this section, we describe the specific methods employed and how they measure the selected variables, thereby discussing the appropriateness of the instrument, providing information about the measurement characteristics of the instruments, and information about the scoring of the scales.  Here it may be useful to recall the conceptual framework presented earlier:

\begin{equation}
\begin{aligned}
Tax Morale_i = & \alpha_i + \beta_1 Trust in Government/Public Officials_i + \beta_2 Level of Corruption_i \\
& + \beta_3 interactions with other taxpayers_i + \beta_4 tax burden_i \\
& + \beta_5 detection and punishment_i + \beta_5 Social Norms_i + \epsilon_i
\end{aligned}
\end{equation}

###Tax Morale
Tax Morale is instrumented by a statement that asks "The tax department always has the right to make people pay taxes" and is measured from "Strongly Disagree", "Disagree", "Neither Agree or Disagree", "Agree" to "Strongly Agree". 

**include summary statistic**

**acknowledge shortcomings of the question** We will further discuss possible limitations of survey-generated information about tax morale in the “limitations and delimitations” section. For now, the reader may bear in mind that measuring tax morale  is a complex task regardless of the method, because it is a construct – a non-tangible phenomenon that needs an indirect form of measurement to be studied.  **elaborate**

###Control Variables
We include **insert number** control variables in our model that provide information about gender, religion, age, country the respondent resides in, **include % of the distribution per variable*** Though studies are not conclusive and often contradictory, we hypothesize that those who claim a religious faith or identity to show more positive attitudes towards paying taxes; based on about the current debats in the financial world and gender differences we further believe women to exhibit higher levels of tax morale than men and older people may be more traditional and conservative than younger ones and thus may be more likely to exhibit higher tax morale and condemn cheating on taxes.

##Analysis Procedure
A regression analysis is used to investigate the determinants of tax morale in African countries, using R Studio [@R; @Stargazer; @knitr] . Since our dependent variable[^1] is measured from  "Strongly Disagree", "Disagree", "Neither Agree or Disagree", "Agree", "Strongly Agree", we believe that the "distances" between these five points are not equal, an OLS regression in this case is problematic because the assumptions of OLS are violated when used with a non-interval outcome variable. Instead, we opted for an ordinal logistic regression. 

In order to use an ordinal logistic regression the following four assumptions need to hold:

1. The dependent variable is measured at the ordinal level.
2. One or more independent variables that are continuous, ordinal, or categorical
3. There is no multicollinearity
4. Ordinal odds

As indicated above, the first assumption holds true; our tax morale variable is measured at the ordinal level. The second assumption also holds true; all of our independent variables, are continuous, ordinal or categorical. To test for multicollinearity, we applied the variance inflation factor; the result are shown in the table below. Since all numbers exept year are very close to 1, we can assert that there is no multicollinearity.

**insert R codes from Assignment 3**

We also created a simply correlation matrix to test for multicollinearity, whose results are depicted in the figure below. As a rule of thumb, any correlation with a value of .5 and above will present multicollinearity, when 1 is perfect correlation. As seen in the correlation matrix, not a singly correlation yields a value above .5. The highest correlation, between country and paying taxes as a self-employed person is only -0.15, far from close to a high, multicollinear correlation.

**insert R codes from Assignment 3**

##Limitations and Delimitations
The following section is dedicated to acknowledging potential limitations and delimitations of the study, thereby addressing possible skepticisms and doubts concerning **??**

#Results and Discussion
This chapter presents the results and discussion of our analysis. We devote one section to discuss the results of the regression analysis, including appropriate robustness checks, before interpreting and discussing the statistical results.

##Regression Analyses
##Discussion

#Conclusion

#References