---
title: "Tax Morale in Africa"
author: "Wiebke Weiger & Jasmin Cantzler"
date: "22 November 2015"
output: 
  revealjs::revealjs_presentation:
    theme: sky
    transition: slide
    highlight: default
bibliography: References.bib
---
```{r, include=FALSE}
# Set working directory
#setwd("C:/Users/Wiebke/Documents/RepRes/TaxMorale/Assignment 3/PreparatoryWork")
setwd("/Users/jasmincantzler/Documents/TaxMorale/Final Project")

library(dplyr)
library(tidyr)
library(googleVis)

# Using the no factor one as we want to show the means in the map
mydata <- read.csv('Afrobarometer.nofactors.csv')

#creates a subset with only Tax Morale and country
summary_df <- mydata %>% 
  group_by(Country) %>% 
  summarise(
    meantaxmorale = mean(TaxMorale, na.rm=TRUE)
  )

TaxMorale_map <- gvisGeoChart(summary_df, locationvar = 'Country',
                      colorvar = 'meantaxmorale',
                      options = list(
                          colors = "['#e31b23', '#ffff00', '#00853f']",
                          region= '002'
                          ))

```

## Tax Morale the Blackbox of Tax Compliance...
<style type="text/css">
p { text-align: left; }
</style>

Tax morale = "the intrinsic motivation to pay taxes"
```{r, results='asis'}
print(TaxMorale_map, tag = 'chart')
```

<br>

## Why Africa?
test test 

## The determinants of tax morale...

$$Tax Morale_i = \alpha_i + \beta_1 Trust in Government_i \\
+ \beta_2 LevelCorruption_i + \beta_3 interactionstaxpayers_i \\ 
+ \beta_4 selfemployed_i + \beta_5 detection and punishment_i + \epsilon_i$$

## How did we arrive at these findings? 
test test 

## References
